### ISSUE TITLE
Ryzen 5 2500U laptop, looking for help

### ISSUE THREAD

**Issue by gty1860** [0nahid/ryzentosh#1]
I have a laptop with Ryzen 5 2500U,8GB ram,512G NVMe SSD.
When using the EFI you release, it fails to boot and displays the following message.
![IMG_0484](https://github.com/0nahid/ryzentosh/assets/96994077/495c0fbb-6d8f-46b2-b78b-25cb6b7dd649)

Is there any modification that can be made to fix it?
Looking forward for help.

**Comment by 0nahid** [comment]
Did you change them MLB/ROM/Serial Number/UUID ?

**Comment by gty1860** [comment]
> Did you change them MLB/ROM/Serial Number/UUID ?

yes, I have them changed and base on MacBookPro16,3

**Comment by 0nahid** [comment]
Send me the logs please.

**Comment by As262** [comment]
> I have a laptop with Ryzen 5 2500U,8GB ram,512G NVMe SSD.
> When using the EFI you release, it fails to boot and displays the following message.
> ![IMG_0484](https://github.com/0nahid/ryzentosh/assets/96994077/495c0fbb-6d8f-46b2-b78b-25cb6b7dd649)
> 
> Is there any modification that can be made to fix it?
> Looking forward for help.
> 
> 

I fixed this problem by downloading the dmg again
