### ISSUE TITLE
SMBios

### ISSUE THREAD

**Issue by StixuYT** [0nahid/ryzentosh#2]
What is the recommended SMBios for this configuration? (r5 3500u, vega 8)

**Comment by 0nahid** [comment]
https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html#macbook-pro
check it out.

or use MacBookPro16,3

**Comment by 0nahid** [comment]
> What is the recommended SMBios for this configuration? (r5 3500u, vega 8)

any update? or should i close this issue
