### ISSUE TITLE
Not showing in Bios 
Edit:- Alps not detected E6 and E7

### ISSUE THREAD

**Issue by As262** [0nahid/ryzentosh#3]
Its not popping up in bios
I disable secure boot in bios
Can you tell me whats the problem?
My laptop specs are 
Lenovo 15ada7
R5 3500u
Ddr4 8gb 2400mhz
512 GB NVME 
Can you tell me which installer you used coz im using online installer

**Comment by 0nahid** [comment]
on which format you've erased your USB?

**Comment by As262** [comment]
Fat32 
I created dmg installer.......or should i make the offline one from olarilla ?
I am New in this 😅

**Comment by As262** [comment]
![image](https://github.com/0nahid/ryzentosh/assets/141184593/cbc373b4-c8c6-4d01-8bfb-bd176ce6df4e)

**Comment by As262** [comment]
![IMG_20230802_110744](https://github.com/0nahid/ryzentosh/assets/141184593/ba164152-2f99-4b62-9908-827e995ac037)

**Comment by 0nahid** [comment]
Use Rufus to make it non bootable first using this:

Boot selection => Non bootable

Partition scheme => GPT

Target system => BIOS or UEFI

**Comment by As262** [comment]
can you send me the link of image file you used to install mac
IM Having a .Raw file and Dmg file of ventura and not a single one format is supported by rufus

**Comment by 0nahid** [comment]
you just need to download the recovery through opencore/utilities/macosrecovery

after that formatting your USB copy the EFI & recovery folder to USB. they try rebooting
make sure you've changed the device configuration such as model, manufacturer, rom etc

**Comment by As262** [comment]
![image](https://github.com/0nahid/ryzentosh/assets/141184593/bfec7591-56a2-41c1-8d8b-aab7512c235d)
you mean change these????
i do changed these but Still No Success🥲

**Comment by 0nahid** [comment]
Then it must issuues with your usb

**Comment by As262** [comment]
So means i need to try cleaning my usb with diskpart?

**Comment by 0nahid** [comment]
> So means i need to try cleaning my usb with diskpart?

yes try that & let me know
when ever i'll free, i'll update new EFI

**Comment by As262** [comment]
Ohk brother thanks
No success again🥲 i tried cleaning using disk part and even after that it didn`t work

**Comment by As262** [comment]
Can you tell that can nooted red cause this problem coz i tried  this one too and same this happens https://github.com/sizeisnoteverything/Acer-Aspire-3-A315-23-Hackintosh

**Comment by As262** [comment]
Somehow i managed to boot into efi and now this error happened any solution ![IMG_20230802_163626.jpg](https://github.com/0nahid/ryzentosh/assets/141184593/d9a45e6b-2c43-4448-8c7d-dce7ddbd5359)

**Comment by 0nahid** [comment]
https://dortania.github.io/OpenCore-Post-Install/usb/manual/manual.html#finding-your-usb-ports

**Comment by As262** [comment]
actually its not the big problem, big one is applePS2controller its the error

**Comment by As262** [comment]
my laptop have 1 port of USB 3.2(on left side), 1 USB 2.0(right side) AND 1 TYPE C (left side)
CAN YOU PLEASE MAP THEM IM NOT ABLE TO UNDERSTAND THAT + I DON`T HAVE MAC

**Comment by As262** [comment]
![IMG_20230802_173702.jpg](https://github.com/0nahid/ryzentosh/assets/141184593/442171e4-4056-401b-adb1-65e9bb5e4355)

This is the error im getting....any solutions for this??

**Comment by As262** [comment]
![IMG_20230803_073122.jpg](https://github.com/0nahid/ryzentosh/assets/141184593/eb06f97b-b490-49de-81c7-4c2c99a070ae)

I tweaked your efi and i solved those issues of usb and touchpad but now this any solutions for apple NVME assert failed?? Thanks

**Comment by As262** [comment]
Anything?
