### ISSUE TITLE
AppleNVME Assert failed 

### ISSUE THREAD

**Issue by As262** [0nahid/ryzentosh#4]

**Comment by As262** [comment]
![IMG_20230803_073122.jpg](https://github.com/0nahid/ryzentosh/assets/141184593/3b5cef6e-a9c8-4231-a036-7fc2c7f0d525)

It boots into nvram but stuck at applenvme assert failed = 0 data.........line 5669
And something

**Comment by 0nahid** [comment]
does it boot into recovery?

**Comment by As262** [comment]
Nope its just 1st opencore menu after selecting new volume just scripts start showing and the. Stop at this error

**Comment by As262** [comment]
Thank you sir You helped me but i figured it why is error is happening.....its because  my nvme is Micron 2200s which is unsupportable by macos 
Thanks again
